Add web
RicharSte/cartoonfilter_ds_project pull request #4
Opened 2020-10-10 12:17 UTC by TverskayN

Добавлена веб-страница с кнопками и неотображаемой формой загрузки файла.

2020-10-10 17:52 UTC, technogleb requested changes
Пока не исправишь текущие замечания, которые не позволяют даже запустить фласк, я не смогу помочь с формами. Исправь как можно скорее плиз)

2020-10-10 17:52 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +from flask import (Flask, render_template)
Скобочки лишние

2020-10-10 17:52 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +        if form.validate_on_submit():
Ээээ, откуда взялся этот form? Это даже синтаксическую проверку не проходит

2020-10-10 17:52 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +            filename = secure_filename(f.filename)
Что за f???

2020-10-10 17:52 UTC, technogleb commented on cartoonfilter_ds_project/webapp/config.py
> +SECRET_KEY = ',Khfbd5ervlit8*^9BjbO(*9iJLkhLO(vdbkFGzc'
1) Эти константы нигде не используются
2)Такие файлы нельзя хранить в гите, их нужно пихать в гитигнор

2020-10-14 20:59 UTC, technogleb requested changes
* В requirements нет flask_wtf, добавь. 
* Твой requirements конфликтует с тем, что в мастере, тебе нужно сделать git merge master, разрешить конфликт у себя в ветке и сделать коммит.
* Чтобы я каждый раз не писал тебе, сколько строчек нужно добавить, сколько убрать, установи pylint и проверяй свой код
* По поводу 302 ошибки - я так понимаю, что ничего плохого в этом нет, страничка photo.html работает. Почему вылезает 302 пока не пойму.

2020-10-14 20:59 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +import os
Негласные правила импортов:
Сначала идут системные библиотеки (те которые доступны без установки pip-ом)
Затем идет пустая строка
Затем идут импорты сторонних библиотек (те, которые ты установила через pip install)
Затем идут внутренние импорты (from webapp import что-то там)
Здесь соотвественно import os должен стоять в самом начале, а так все правильно.

2020-10-14 20:59 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +
Здесь нужны две строки отступа

2020-10-14 20:59 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +    def allowed_file(filename):
Молодец, хорошая функция!

2020-10-14 20:59 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +            # кладем файл из запроса в file
Лишний комментарий, потому что код говорит сам за себя, комментарии тут не нужны.

2020-10-14 20:59 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +                file.save(os.path.abspath(os.path.join("downloads", filename)))
Молодец, хорошо с 25 по 36 строчку!

2020-10-14 20:59 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +            if request.file_form['processing'] == 'cortoon_filter': # обработка фильтрами
cortoon? Точно не опечатка?

2020-10-14 20:59 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +            elif request.file_form['processing'] == 'neural_network': # обработка ИИ
Данные условные операторы отличаются лишь flash-ом? Ну такое... получается, что чтобы ни выбрал пользователь, все равно будет вызван один и тот же photo_processing.

2020-10-14 20:59 UTC, technogleb commented on cartoonfilter_ds_project/webapp/forms.py
> +
Тут две строки нужны.

2020-10-14 20:59 UTC, technogleb commented on cartoonfilter_ds_project/webapp/forms.py
> +    photo = FileField('картинка', validators=[FileRequired()],
Что-то с переносом строк

2020-10-14 20:59 UTC, technogleb commented on cartoonfilter_ds_project/webapp/__init__.py
> +
нужно всего 2 лишние строчки

2020-10-15 01:29 UTC, TverskayN commented on cartoonfilter_ds_project/webapp/__init__.py
> +            if request.file_form['processing'] == 'cortoon_filter': # обработка фильтрами
Да, опечатка, спасибо!

2020-10-15 01:31 UTC, TverskayN commented on cartoonfilter_ds_project/webapp/__init__.py
> +            elif request.file_form['processing'] == 'neural_network': # обработка ИИ
Там еще будет обработка фотографий

2020-10-17 08:16 UTC, technogleb commented
Отлично, закрываю пулл-реквест!

2020-10-17 08:16 UTC, merged